// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::game_state_type::GameState;
use super::game_type::Game;
use super::player_type::Player;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game`.
///
/// Obtain a handle from the [`GameTableAccess::game`] method on [`super::RemoteTables`],
/// like `ctx.db.game()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game().on_insert(...)`.
pub struct GameTableHandle<'ctx> {
    imp: __sdk::TableHandle<Game>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameTableHandle`], which mediates access to the table `game`.
    fn game(&self) -> GameTableHandle<'_>;
}

impl GameTableAccess for super::RemoteTables {
    fn game(&self) -> GameTableHandle<'_> {
        GameTableHandle {
            imp: self.imp.get_table::<Game>("game"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameInsertCallbackId(__sdk::CallbackId);
pub struct GameDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameTableHandle<'ctx> {
    type Row = Game;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Game> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameInsertCallbackId {
        GameInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameDeleteCallbackId {
        GameDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Game>("game");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct GameUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameTableHandle<'ctx> {
    type UpdateCallbackId = GameUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameUpdateCallbackId {
        GameUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Game>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Game>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `game`,
/// which allows point queries on the field of the same name
/// via the [`GameIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game().id().find(...)`.
pub struct GameIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Game, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game`.
    pub fn id(&self) -> GameIdUnique<'ctx> {
        GameIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Game> {
        self.imp.find(col_val)
    }
}
