// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::game_duration_time_schedule_type::GameDurationTimeSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_duration_time_schedule`.
///
/// Obtain a handle from the [`GameDurationTimeScheduleTableAccess::game_duration_time_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.game_duration_time_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_duration_time_schedule().on_insert(...)`.
pub struct GameDurationTimeScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<GameDurationTimeSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_duration_time_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameDurationTimeScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameDurationTimeScheduleTableHandle`], which mediates access to the table `game_duration_time_schedule`.
    fn game_duration_time_schedule(&self) -> GameDurationTimeScheduleTableHandle<'_>;
}

impl GameDurationTimeScheduleTableAccess for super::RemoteTables {
    fn game_duration_time_schedule(&self) -> GameDurationTimeScheduleTableHandle<'_> {
        GameDurationTimeScheduleTableHandle {
            imp: self
                .imp
                .get_table::<GameDurationTimeSchedule>("game_duration_time_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameDurationTimeScheduleInsertCallbackId(__sdk::CallbackId);
pub struct GameDurationTimeScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameDurationTimeScheduleTableHandle<'ctx> {
    type Row = GameDurationTimeSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameDurationTimeSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameDurationTimeScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameDurationTimeScheduleInsertCallbackId {
        GameDurationTimeScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameDurationTimeScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameDurationTimeScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameDurationTimeScheduleDeleteCallbackId {
        GameDurationTimeScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameDurationTimeScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<GameDurationTimeSchedule>("game_duration_time_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct GameDurationTimeScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameDurationTimeScheduleTableHandle<'ctx> {
    type UpdateCallbackId = GameDurationTimeScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameDurationTimeScheduleUpdateCallbackId {
        GameDurationTimeScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameDurationTimeScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GameDurationTimeSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GameDurationTimeSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `game_duration_time_schedule`,
/// which allows point queries on the field of the same name
/// via the [`GameDurationTimeScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_duration_time_schedule().scheduled_id().find(...)`.
pub struct GameDurationTimeScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GameDurationTimeSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameDurationTimeScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `game_duration_time_schedule`.
    pub fn scheduled_id(&self) -> GameDurationTimeScheduleScheduledIdUnique<'ctx> {
        GameDurationTimeScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameDurationTimeScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GameDurationTimeSchedule> {
        self.imp.find(col_val)
    }
}
