// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct JoinGameArgs {
    pub room_id: u32,
}

impl From<JoinGameArgs> for super::Reducer {
    fn from(args: JoinGameArgs) -> Self {
        Self::JoinGame {
            room_id: args.room_id,
        }
    }
}

impl __sdk::InModule for JoinGameArgs {
    type Module = super::RemoteModule;
}

pub struct JoinGameCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `join_game`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait join_game {
    /// Request that the remote module invoke the reducer `join_game` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_join_game`] callbacks.
    fn join_game(&self, room_id: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `join_game`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`JoinGameCallbackId`] can be passed to [`Self::remove_on_join_game`]
    /// to cancel the callback.
    fn on_join_game(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> JoinGameCallbackId;
    /// Cancel a callback previously registered by [`Self::on_join_game`],
    /// causing it not to run in the future.
    fn remove_on_join_game(&self, callback: JoinGameCallbackId);
}

impl join_game for super::RemoteReducers {
    fn join_game(&self, room_id: u32) -> __sdk::Result<()> {
        self.imp.call_reducer("join_game", JoinGameArgs { room_id })
    }
    fn on_join_game(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> JoinGameCallbackId {
        JoinGameCallbackId(self.imp.on_reducer(
            "join_game",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::JoinGame { room_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, room_id)
            }),
        ))
    }
    fn remove_on_join_game(&self, callback: JoinGameCallbackId) {
        self.imp.remove_on_reducer("join_game", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `join_game`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_join_game {
    /// Set the call-reducer flags for the reducer `join_game` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn join_game(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_join_game for super::SetReducerFlags {
    fn join_game(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("join_game", flags);
    }
}
