// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LeaveGameArgs {
    pub game_id: String,
}

impl From<LeaveGameArgs> for super::Reducer {
    fn from(args: LeaveGameArgs) -> Self {
        Self::LeaveGame {
            game_id: args.game_id,
        }
    }
}

impl __sdk::InModule for LeaveGameArgs {
    type Module = super::RemoteModule;
}

pub struct LeaveGameCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `leave_game`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait leave_game {
    /// Request that the remote module invoke the reducer `leave_game` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_leave_game`] callbacks.
    fn leave_game(&self, game_id: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `leave_game`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`LeaveGameCallbackId`] can be passed to [`Self::remove_on_leave_game`]
    /// to cancel the callback.
    fn on_leave_game(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> LeaveGameCallbackId;
    /// Cancel a callback previously registered by [`Self::on_leave_game`],
    /// causing it not to run in the future.
    fn remove_on_leave_game(&self, callback: LeaveGameCallbackId);
}

impl leave_game for super::RemoteReducers {
    fn leave_game(&self, game_id: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("leave_game", LeaveGameArgs { game_id })
    }
    fn on_leave_game(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> LeaveGameCallbackId {
        LeaveGameCallbackId(self.imp.on_reducer(
            "leave_game",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::LeaveGame { game_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, game_id)
            }),
        ))
    }
    fn remove_on_leave_game(&self, callback: LeaveGameCallbackId) {
        self.imp.remove_on_reducer("leave_game", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `leave_game`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_leave_game {
    /// Set the call-reducer flags for the reducer `leave_game` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn leave_game(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_leave_game for super::SetReducerFlags {
    fn leave_game(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("leave_game", flags);
    }
}
