// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkCellArgs {
    pub game_id: String,
    pub cell: u16,
}

impl From<MarkCellArgs> for super::Reducer {
    fn from(args: MarkCellArgs) -> Self {
        Self::MarkCell {
            game_id: args.game_id,
            cell: args.cell,
        }
    }
}

impl __sdk::InModule for MarkCellArgs {
    type Module = super::RemoteModule;
}

pub struct MarkCellCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_cell`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_cell {
    /// Request that the remote module invoke the reducer `mark_cell` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_mark_cell`] callbacks.
    fn mark_cell(&self, game_id: String, cell: u16) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `mark_cell`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MarkCellCallbackId`] can be passed to [`Self::remove_on_mark_cell`]
    /// to cancel the callback.
    fn on_mark_cell(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &u16) + Send + 'static,
    ) -> MarkCellCallbackId;
    /// Cancel a callback previously registered by [`Self::on_mark_cell`],
    /// causing it not to run in the future.
    fn remove_on_mark_cell(&self, callback: MarkCellCallbackId);
}

impl mark_cell for super::RemoteReducers {
    fn mark_cell(&self, game_id: String, cell: u16) -> __sdk::Result<()> {
        self.imp
            .call_reducer("mark_cell", MarkCellArgs { game_id, cell })
    }
    fn on_mark_cell(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &u16) + Send + 'static,
    ) -> MarkCellCallbackId {
        MarkCellCallbackId(self.imp.on_reducer(
            "mark_cell",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MarkCell { game_id, cell },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, game_id, cell)
            }),
        ))
    }
    fn remove_on_mark_cell(&self, callback: MarkCellCallbackId) {
        self.imp.remove_on_reducer("mark_cell", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `mark_cell`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_mark_cell {
    /// Set the call-reducer flags for the reducer `mark_cell` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn mark_cell(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_mark_cell for super::SetReducerFlags {
    fn mark_cell(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("mark_cell", flags);
    }
}
