// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::game_duration_time_schedule_type::GameDurationTimeSchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ScheduledTurnExpirationArgs {
    pub arg: GameDurationTimeSchedule,
}

impl From<ScheduledTurnExpirationArgs> for super::Reducer {
    fn from(args: ScheduledTurnExpirationArgs) -> Self {
        Self::ScheduledTurnExpiration { arg: args.arg }
    }
}

impl __sdk::InModule for ScheduledTurnExpirationArgs {
    type Module = super::RemoteModule;
}

pub struct ScheduledTurnExpirationCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `scheduled_turn_expiration`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait scheduled_turn_expiration {
    /// Request that the remote module invoke the reducer `scheduled_turn_expiration` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_scheduled_turn_expiration`] callbacks.
    fn scheduled_turn_expiration(&self, arg: GameDurationTimeSchedule) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `scheduled_turn_expiration`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ScheduledTurnExpirationCallbackId`] can be passed to [`Self::remove_on_scheduled_turn_expiration`]
    /// to cancel the callback.
    fn on_scheduled_turn_expiration(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &GameDurationTimeSchedule) + Send + 'static,
    ) -> ScheduledTurnExpirationCallbackId;
    /// Cancel a callback previously registered by [`Self::on_scheduled_turn_expiration`],
    /// causing it not to run in the future.
    fn remove_on_scheduled_turn_expiration(&self, callback: ScheduledTurnExpirationCallbackId);
}

impl scheduled_turn_expiration for super::RemoteReducers {
    fn scheduled_turn_expiration(&self, arg: GameDurationTimeSchedule) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "scheduled_turn_expiration",
            ScheduledTurnExpirationArgs { arg },
        )
    }
    fn on_scheduled_turn_expiration(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &GameDurationTimeSchedule)
            + Send
            + 'static,
    ) -> ScheduledTurnExpirationCallbackId {
        ScheduledTurnExpirationCallbackId(self.imp.on_reducer(
            "scheduled_turn_expiration",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ScheduledTurnExpiration { arg },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, arg)
            }),
        ))
    }
    fn remove_on_scheduled_turn_expiration(&self, callback: ScheduledTurnExpirationCallbackId) {
        self.imp
            .remove_on_reducer("scheduled_turn_expiration", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `scheduled_turn_expiration`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_scheduled_turn_expiration {
    /// Set the call-reducer flags for the reducer `scheduled_turn_expiration` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn scheduled_turn_expiration(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_scheduled_turn_expiration for super::SetReducerFlags {
    fn scheduled_turn_expiration(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("scheduled_turn_expiration", flags);
    }
}
